// Okinawa Designated Evacuation Shelters Database
export const shelters = [
  {
    id: "shelter-naha-01",
    name: "Naha Civic Center (Naha Shimin Kaikan)",
    nameJa: "那覇市民会館",
    municipality: "Naha",
    municipalityJa: "那覇市",
    address: "2-1-1 Yorimiya, Naha, Okinawa",
    addressJa: "沖縄県那覇市寄宮2-1-1",
    latitude: 26.2125,
    longitude: 127.6972,
    tsunamiSafe: true,
    earthquakeResistant: true,
    floodSafe: true,
    capacity: 1500,
    currentOccupancy: 342,
    status: "Open", // Open, Full, Closed
    amenities: ["Emergency Power", "Food Supply", "Potable Water", "Medical Station", "English Support"],
    contact: "098-867-0111"
  },
  {
    id: "shelter-naha-02",
    name: "Okinawa Prefectural Government Office Plaza",
    nameJa: "沖縄県庁前広場・庁舎",
    municipality: "Naha",
    municipalityJa: "那覇市",
    address: "1-2-2 Izumizaki, Naha, Okinawa",
    addressJa: "沖縄県那覇市泉崎1-2-2",
    latitude: 26.2124,
    longitude: 127.6809,
    tsunamiSafe: true, // High elevation office building floors
    earthquakeResistant: true,
    floodSafe: true,
    capacity: 2000,
    currentOccupancy: 850,
    status: "Open",
    amenities: ["Emergency Power", "Potable Water", "Satellite Telecom", "Helipad"],
    contact: "098-866-2333"
  },
  {
    id: "shelter-nago-01",
    name: "Nago Civic Hall (Nago Shimin Kaikan)",
    nameJa: "名護市民会館",
    municipality: "Nago",
    municipalityJa: "名護市",
    address: "2-1-1 Minato, Nago, Okinawa",
    addressJa: "沖縄県名護市港2-1-1",
    latitude: 26.5914,
    longitude: 127.9774,
    tsunamiSafe: false, // Near the shore - not recommended for high tsunamis
    earthquakeResistant: true,
    floodSafe: true,
    capacity: 1000,
    currentOccupancy: 120,
    status: "Open",
    amenities: ["Food Supply", "Potable Water", "Blankets"],
    contact: "0980-53-1212"
  },
  {
    id: "shelter-nago-02",
    name: "Nago Castle Park (High Ground)",
    nameJa: "名護城公園 (高台避難所)",
    municipality: "Nago",
    municipalityJa: "名護市",
    address: "5511 Nago, Nago, Okinawa",
    addressJa: "沖縄県名護市名護5511 (名護城趾)",
    latitude: 26.5878,
    longitude: 127.9897,
    tsunamiSafe: true, // Excellent elevation (Mt. Nago)
    earthquakeResistant: true, // Outdoor open safe zone / shelter structures
    floodSafe: true,
    capacity: 3000,
    currentOccupancy: 0,
    status: "Open",
    amenities: ["Emergency Supplies Box", "Helipad", "Solar Lights"],
    contact: "0980-53-5311"
  },
  {
    id: "shelter-okinawa-01",
    name: "Okinawa City Gymnasium",
    nameJa: "沖縄市体育館",
    municipality: "Okinawa City",
    municipalityJa: "沖縄市",
    address: "2-1-1 Moromizato, Okinawa City, Okinawa",
    addressJa: "沖縄県沖縄市諸見里2-1-1",
    latitude: 26.3245,
    longitude: 127.7944,
    tsunamiSafe: true, // Elevated central area
    earthquakeResistant: true,
    floodSafe: true,
    capacity: 2500,
    currentOccupancy: 2450,
    status: "Full",
    amenities: ["Emergency Power", "Food Supply", "Potable Water", "Medical Station", "Showers"],
    contact: "098-932-1212"
  },
  {
    id: "shelter-uruma-01",
    name: "Uruma Civic Center",
    nameJa: "うるま市民芸術劇場",
    municipality: "Uruma",
    municipalityJa: "うるま市",
    address: "907 Enobi, Uruma, Okinawa",
    addressJa: "沖縄県うるま市字絵野比907",
    latitude: 26.3778,
    longitude: 127.8386,
    tsunamiSafe: true,
    earthquakeResistant: true,
    floodSafe: true,
    capacity: 1200,
    currentOccupancy: 45,
    status: "Open",
    amenities: ["Potable Water", "Blankets", "Emergency Power"],
    contact: "098-973-4400"
  },
  {
    id: "shelter-ishigaki-01",
    name: "Ishigaki City Hall (New Building - High Ground)",
    nameJa: "石垣市役所 (新庁舎・高台)",
    municipality: "Ishigaki",
    municipalityJa: "石垣市",
    address: "Yaeyama, Ishigaki, Okinawa (Maezato Area)",
    addressJa: "沖縄県石垣市真栄里 (高台移転新庁舎)",
    latitude: 24.3486,
    longitude: 124.1797,
    tsunamiSafe: true, // Relocated specifically to high ground for tsunami safety
    earthquakeResistant: true,
    floodSafe: true,
    capacity: 1800,
    currentOccupancy: 95,
    status: "Open",
    amenities: ["Emergency Power", "Food Supply", "Potable Water", "Satellite Telecom", "Medical Station"],
    contact: "0980-82-9911"
  },
  {
    id: "shelter-miyakojima-01",
    name: "Miyakojima City Sports Park Gymnasium",
    nameJa: "宮古島市総合体育館",
    municipality: "Miyakojima",
    municipalityJa: "宮古島市",
    address: "Hirara Higashinakasone, Miyakojima, Okinawa",
    addressJa: "沖縄県宮古島市平良東仲宗根",
    latitude: 24.7981,
    longitude: 125.2917,
    tsunamiSafe: true,
    earthquakeResistant: true,
    floodSafe: true,
    capacity: 1500,
    currentOccupancy: 210,
    status: "Open",
    amenities: ["Emergency Power", "Food Supply", "Potable Water", "Blankets"],
    contact: "0980-73-1111"
  }
];
